### ISSUE TITLE
gulp-watch ELIFECYCLE  error

### ISSUE THREAD

**Issue by xjonsson** [wuifdesign/eve-online-mining-timer#5]
After the update to package versions gulp-watch is giving some issues

`npm run dev-server` works great and as expected

`npm run gulp-watch` gives ELIFECYCLE error

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/xdev/.nvm/versions/v12.16.3/bin/node',
1 verbose cli   '/Users/xdev/.nvm/versions/v12.16.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'gulp-watch'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.3
4 verbose run-script [ 'pregulp-watch', 'gulp-watch', 'postgulp-watch' ]
5 info lifecycle @~pregulp-watch: @
6 info lifecycle @~gulp-watch: @
7 verbose lifecycle @~gulp-watch: unsafe-perm in lifecycle true
8 verbose lifecycle @~gulp-watch: PATH: /Users/xdev/.nvm/versions/v12.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/xdev/Documents/xDev/eve-online-mining-timer/node_modules/.bin:/Users/xdev/.nvm/versions/v12.16.3/bin:/Users/xdev/.nvm/versions/v14.4.0/bin:/Users/xdev/.nvm/versions/v12.16.3/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/opt/qt/bin:/System/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/bin:/Users/xdev/perl5/perlbrew/bin:/Users/xdev/perl5/perlbrew/perls/perl-5.20.1/bin:/Users/xdev/.rbenv/shims:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
9 verbose lifecycle @~gulp-watch: CWD: /Users/xdev/Documents/xDev/eve-online-mining-timer
10 silly lifecycle @~gulp-watch: Args: [ '-c', 'gulp watch' ]
11 silly lifecycle @~gulp-watch: Returned: code: 1  signal: null
12 info lifecycle @~gulp-watch: Failed to exec gulp-watch script
13 verbose stack Error: @ gulp-watch: `gulp watch`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/xdev/.nvm/versions/v12.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (/Users/xdev/.nvm/versions/v12.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid @
15 verbose cwd /Users/xdev/Documents/xDev/eve-online-mining-timer
16 verbose Darwin 18.7.0
17 verbose argv "/Users/xdev/.nvm/versions/v12.16.3/bin/node" "/Users/xdev/.nvm/versions/v12.16.3/bin/npm" "run" "gulp-watch"
18 verbose node v12.16.3
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error @ gulp-watch: `gulp watch`
22 error Exit status 1
23 error Failed at the @ gulp-watch script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Upgraded to node 12.16.3 just to be sure and on clean repo but will dig into it a bit more and see what we can do

**Comment by wuifdesign** [comment]
thx, missed to update 1 file for the gulp 4 update

**Comment by xjonsson** [comment]
Ah awesome, i tried fixing it but dont know gulp 4 and the whole parallel / series thing
